### ISSUE TITLE
What's this plugin do?

### ISSUE THREAD

**Issue by ThimbleFire** [geel9/runelite-custom-item-hovers#1]
Could you please go into detail on what a custom hover can do and what it looks like?
Is it a kind of tooltip allowing for user's to customize what is shown?
Custom hover sounds interesting but the readme doesn't tell me anything about the plugin.

**Comment by geel9** [comment]
It allows you to create, via JSON files, custom hovers for items that give you useful information about them at a glance.

For example:

![image](https://user-images.githubusercontent.com/1294419/107907293-49effa80-6f21-11eb-9a89-f04c82983231.png)
![image](https://user-images.githubusercontent.com/1294419/107907300-51af9f00-6f21-11eb-8abe-478102578f6f.png)
![image](https://user-images.githubusercontent.com/1294419/107907315-5d9b6100-6f21-11eb-82da-f4395cfb1250.png)
![image](https://user-images.githubusercontent.com/1294419/107907328-655b0580-6f21-11eb-8cff-1a4af8653516.png)


It supports hot-reloading, so changes you make apply live.

Truth be told, I only really published this so I could use it on my main, non-dev-mode client. So I can't promise anything with regards to maintenance.
