### ISSUE TITLE
Enable Discussions Tab for Configuration Sharing

### ISSUE THREAD

**Issue by Kydoimos97** [geel9/runelite-custom-item-hovers#10]
## Feature Request: Enable Discussions Tab for Configuration Sharing

First of all great plugin I love the ability to customize the hovers to show the information I need, nothing less or more. 

I'd like  propose enabling the Discussions tab on GitHub to create a dedicated space for users to share, discuss, and enhance JSON configurations. This would allow the community to build a comprehensive knowledge base and provide concrete examples for new users.

### Detail
The repository could benefit from a structured environment where users can share their custom JSON configurations. This would not only aid in shared knowledge building but also in improving the usability and adaptability of the plugin through quicker setup.

### Benefits
- **Focused Knowledge Sharing**: Centralizes the sharing of user-created JSON configurations, making it easier for users to find and utilize them to setup the plugin quicker.
- **Enhanced Learning for New Users**: Provides newcomers with more practical examples and the opportunity to learn from existing configurations.
- **Community Contributions**: Encourages users to contribute their configurations, which can be iteratively refined and expanded upon through community feedback.

Thank you again for developing this plugin! 🥇

**Comment by geel9** [comment]
I have enabled discussions
