### ISSUE TITLE
Add hovers based on Item IDs?

### ISSUE THREAD

**Issue by Koslas1** [geel9/runelite-custom-item-hovers#11]
Is it possible to do something like this

{
  "is_hover_map": "absolutely",
  "hovers": [
    {
      "item_id": [25789],
      "hovers": [
        ["Search the crates in the fruit store just east of the Hosidius town centre."]
      ]
    }
}

As clue scroll (easy) all have the same item name, however their item ID's are different (Except beginner and master), which would allow you to do something like this, which would tell you what the clue step is, without opening the clue scroll

**Comment by geel9** [comment]
This is actually possible -- instead of `item_id`, use `ids`

EG:

```
{
	"is_hover_map": "absolutely",
	"hovers": [
	{
		"ids": [25789],
		"hovers": [
			["Search the crates in the fruit store just east of the Hosidius town centre."]
		]
	}
}
```

**Comment by Koslas1** [comment]
Oh thanks for the reply of getting back to me, I didn't see anything about using item ids in any of your documentation (Which is rather detailed and helpful, so thanks for that).
Could I suggest adding this somewhere in the documentation?
