### ISSUE TITLE
Hover no longer works

### ISSUE THREAD

**Issue by slyyyyyy** [geel9/runelite-custom-item-hovers#2]
Edited the ensouled heads JSON to be updated to the new rune requirements and somehow broke it. Deleted it and redownloaded the one you have as an example and now no hover text appears at all. Created new JSON files, uninstalled and reinstalled plugin making sure it deleted it correctly, not sure what else the issue can be. Doesn't show the text for other things like the farming example either. Not sure if you still actively monitor this.

**Comment by geel9** [comment]
Strange; the plugin is still working just fine for me.

I've attached the contents of my `customitemhovers` folder. Could you please extract it (deleting / moving elsewhere *any* files that are presently in that folder*)?


Assuming you're using Windows, these .json files go in a folder located at:

`C:/Users/{YourWindowsUsername}/.runelite/customitemhovers/`

(You seem to already know where this folder is, but just to make sure)

**Comment by geel9** [comment]
Just realized I never actually attached anything... my bad.


[customitemhovers.zip](https://github.com/geel9/runelite-custom-item-hovers/files/7027628/customitemhovers.zip)
