### ISSUE TITLE
Add qty divide function

### ISSUE THREAD

**Issue by Z7-z** [geel9/runelite-custom-item-hovers#4]
I haven't got a big brain so if it's possible to divide already then wonderful but to make it easy I am asking for the opposite of qtymult basically, to divide instead. This would be useful particularly in the new update where 1 blessed sunfire wine is enough for 400 of your shards so I was planning to add a hover on my shards that would divide by 400 to tell me how many jugs I need and instead of using a calculator I'm writing this instead. 

Thank you

**Comment by geel9** [comment]
Resolved by fa5fea5bbec176a11f84c4b6ce6b279558727043; will be deployed whenever RuneLite accepts the [plugin hub PR](https://github.com/runelite/plugin-hub/pull/5785)
